/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as tradingContractCw1Sol from "./TradingContractCW1.sol";
export * as pokemonNftSol from "./pokemonNFT.sol";
