/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as tradingContractCw1Sol from "./TradingContractCW1.sol";
export type { tradingContractCw1Sol };
import type * as pokemonNftSol from "./pokemonNFT.sol";
export type { pokemonNftSol };
